### ISSUE TITLE
ReferenceError: readCodepointsFromFile is not defined

### ISSUE THREAD

**Issue by askmatey** [jvanaert/gulp-webfont#2]

**Comment by jvanaert** [comment]
do you have a bit more info about this problem?
os? node version? what steps to reproduce the error ?
Thanks !

**Comment by jvanaert** [comment]
sorry for the stupid questions above.
Looks like I didn't copy the readCodepointsFromFile from the grunt-webfont repo, as I didn't need that functionality in my own project.
If you need the readCodepointsFromFile functionality,  I am welcoming your PR ;)

**Comment by wesflo** [comment]
This Bug still exists - but i don't have the rights to pull some bugfix branch:

> Pushing to https://github.com/jvanaert/gulp-webfont.git
remote: Permission to jvanaert/gulp-webfont.git denied to wesflo.
fatal: unable to access 'https://github.com/jvanaert/gulp-webfont.git/': The requested URL returned error: 403
